name: CI Pipeline

on:
    push:
        branches:
            - develop
            - master
    pull_request:
        branches:
            - develop
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '8.0.0'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build -c Release

            - name: Publish
              run: dotnet publish -c Release -o ./publish

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: published-files
                  path: ./publish
